import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/*
 *  Klasa Wypozyczenia
 *
 *  Klasa pozwala na przejrzenie wypozyczen, zwrocenie wybranych wypozyczen,
 *  oraz przejrzenie wypozyczen wybranego klienta.
 *
 *  Autor: Adam Filipowicz
 *  Data: 2 sierpnia 2017 r.
 */
public class Wypozyczenia extends javax.swing.JFrame {
    private String nazwaKonta;
    private Wypozyczenie wyp;
    protected static OpcjeS opcje;
    private int numerWypozyczenia;
    protected Wypozyczalnia wypozyczalnia;
    protected static JOptionUserDialog UI = new JOptionUserDialog();
    
    private Wypozyczenia() {}
    
    public Wypozyczenia(String nazwaKonta, Wypozyczalnia wypozyczalnia) throws SQLException{
        initComponents();
        this.nazwaKonta = nazwaKonta;
        this.wypozyczalnia = wypozyczalnia;
        numerWypozyczenia=1;
        aktualizujWypozyczenie();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        iloscText = new javax.swing.JTextField();
        opisText = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        nazwaText = new javax.swing.JTextField();
        poprzednieWypButton = new javax.swing.JButton();
        nastepneWypButton = new javax.swing.JButton();
        cenaText = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        dataWypText = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        nazwaKlientaText = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        dataZwrText = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        czyZwrocony = new javax.swing.JCheckBox();
        historiaKlientaButton1 = new javax.swing.JButton();
        historiaButton1 = new javax.swing.JButton();
        zwrocButton = new javax.swing.JButton();
        wrocSButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Edytuj filmy");

        iloscText.setEditable(false);

        opisText.setEditable(false);

        jTextField5.setEditable(false);
        jTextField5.setText("Nazwa klienta");

        jTextField6.setEditable(false);
        jTextField6.setText("Ilosc");

        jTextField7.setEditable(false);
        jTextField7.setText("Cena");

        jTextField8.setEditable(false);
        jTextField8.setText("Opis");

        nazwaText.setEditable(false);

        poprzednieWypButton.setText("Poprzednie wypozyczenie");
        poprzednieWypButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poprzednieWypButtonActionPerformed(evt);
            }
        });

        nastepneWypButton.setText("Nastepne wypozyczenie");
        nastepneWypButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nastepneWypButtonActionPerformed(evt);
            }
        });

        cenaText.setEditable(false);

        jTextField9.setEditable(false);
        jTextField9.setText("Nazwa filmu");

        dataWypText.setEditable(false);

        jTextField10.setEditable(false);
        jTextField10.setText("Data wypozyczenia");

        nazwaKlientaText.setEditable(false);

        jTextField11.setEditable(false);
        jTextField11.setText("Data zwrotu");

        dataZwrText.setEditable(false);

        jTextField12.setEditable(false);
        jTextField12.setText("Czy zwrocony");

        czyZwrocony.setEnabled(false);

        historiaKlientaButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        historiaKlientaButton1.setText("Sprawdz historie klienta");
        historiaKlientaButton1.setToolTipText("");
        historiaKlientaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historiaKlientaButton1ActionPerformed(evt);
            }
        });

        historiaButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        historiaButton1.setText("Sprawdz cala historie");
        historiaButton1.setToolTipText("");
        historiaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historiaButton1ActionPerformed(evt);
            }
        });

        zwrocButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        zwrocButton.setText("Zwroc wypozyczenie");
        zwrocButton.setToolTipText("");
        zwrocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zwrocButtonActionPerformed(evt);
            }
        });

        wrocSButton12.setText("Wroc do menu glownego");
        wrocSButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrocSButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(poprzednieWypButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nastepneWypButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(305, 305, 305)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(opisText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(iloscText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nazwaText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dataWypText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nazwaKlientaText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dataZwrText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cenaText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(77, 77, 77)
                                        .addComponent(czyZwrocony)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(historiaButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(zwrocButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(historiaKlientaButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(wrocSButton12)
                .addGap(277, 277, 277))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nazwaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nazwaKlientaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataWypText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataZwrText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cenaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iloscText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(opisText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(czyZwrocony)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(historiaKlientaButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(historiaButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(zwrocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nastepneWypButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(poprzednieWypButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(wrocSButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void poprzednieWypButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poprzednieWypButtonActionPerformed
        if(numerWypozyczenia>1){
            numerWypozyczenia--;
            try {
                aktualizujWypozyczenie();
            } catch (Exception ex) {
                UI.printErrorMessage(ex.getMessage());
                return;
            }
        }
    }//GEN-LAST:event_poprzednieWypButtonActionPerformed
        
    private void nastepneWypButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nastepneWypButtonActionPerformed
        numerWypozyczenia++;
        try {
            aktualizujWypozyczenie();
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
    }//GEN-LAST:event_nastepneWypButtonActionPerformed

    private void historiaKlientaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historiaKlientaButton1ActionPerformed
        String nazwaKonta;
        String kontoKlienta;
        nazwaKonta = UI.enterString("Podaj nazwe konta klienta: ");
        try {
            kontoKlienta=wypozyczalnia.znajdzKonto(nazwaKonta);
            if(kontoKlienta==null){
                UI.printErrorMessage("\nBledna nazwa konta");
                return;
            }
            UI.printMessage("\nHISTORIA ZAKUPOW KLIENTA " + nazwaKonta);
            UI.printInfoMessage(wypozyczalnia.wyswietlHistorieWypozyczenKlienta(kontoKlienta));
        } catch (Exception e) {
            UI.printErrorMessage(e.getMessage());
            return;
        }
    }//GEN-LAST:event_historiaKlientaButton1ActionPerformed

    private void historiaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historiaButton1ActionPerformed
        UI.printMessage("\nHISTORIA ZAKUPOW");
        try {
            UI.printInfoMessage(wypozyczalnia.wyswietlHistorieWypozyczen());
        } catch (Exception e) {
            UI.printErrorMessage(e.getMessage());
            return;
        }
    }//GEN-LAST:event_historiaButton1ActionPerformed

    private void zwrocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zwrocButtonActionPerformed
        try {
            if(!czyZwrocony.isSelected())
                wypozyczalnia.setZwrocony(numerWypozyczenia);
            else{
                UI.printErrorMessage("Film zostal juz wczesniej zwrocony");
                return;
            }
            if(wypozyczalnia.znajdzFilm(nazwaText.getText()));
                wypozyczalnia.dodajIlosc(nazwaText.getText(),Integer.parseInt(iloscText.getText()));
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
        UI.printInfoMessage("Film zwrocony");
        try {
            aktualizujWypozyczenie();
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
    }//GEN-LAST:event_zwrocButtonActionPerformed

    private void wrocSButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrocSButton12ActionPerformed
        try {
            opcje = new OpcjeS(nazwaKonta, wypozyczalnia);
        } catch (Exception e) {
            UI.printErrorMessage(e.getMessage());
            return;
        }
        opcje.setResizable(false);
        opcje.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        opcje.setSize(800,500);
        opcje.setLocation(500,250);
        opcje.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_wrocSButton12ActionPerformed

    public void aktualizujWypozyczenie() throws SQLException{
        wyp = wypozyczalnia.znajdzWypozyczenieCale(numerWypozyczenia);
        if(wyp==null){
            numerWypozyczenia--;
            return;
        }
        nazwaText.setText(wyp.getNazwaFilmu());
        nazwaKlientaText.setText(wyp.getNazwaKlienta());
        dataWypText.setText(wyp.getDataWypozyczenia());
        dataZwrText.setText(wyp.getDataZwrotu());
        cenaText.setText(Double.toString(wyp.getCena()));
        iloscText.setText(Integer.toString(wyp.getIlosc()));
        opisText.setText(wyp.getOpis());
        czyZwrocony.setSelected(wyp.getZwrocony());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZmienFilmy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZmienFilmy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZmienFilmy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZmienFilmy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wypozyczenia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cenaText;
    private javax.swing.JCheckBox czyZwrocony;
    private javax.swing.JTextField dataWypText;
    private javax.swing.JTextField dataZwrText;
    private javax.swing.JButton historiaButton1;
    private javax.swing.JButton historiaKlientaButton1;
    private javax.swing.JTextField iloscText;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton nastepneWypButton;
    private javax.swing.JTextField nazwaKlientaText;
    private javax.swing.JTextField nazwaText;
    private javax.swing.JTextField opisText;
    private javax.swing.JButton poprzednieWypButton;
    private javax.swing.JButton wrocSButton;
    private javax.swing.JButton wrocSButton1;
    private javax.swing.JButton wrocSButton10;
    private javax.swing.JButton wrocSButton11;
    private javax.swing.JButton wrocSButton12;
    private javax.swing.JButton wrocSButton2;
    private javax.swing.JButton wrocSButton3;
    private javax.swing.JButton wrocSButton4;
    private javax.swing.JButton wrocSButton5;
    private javax.swing.JButton wrocSButton6;
    private javax.swing.JButton wrocSButton7;
    private javax.swing.JButton wrocSButton8;
    private javax.swing.JButton wrocSButton9;
    private javax.swing.JButton zwrocButton;
    // End of variables declaration//GEN-END:variables
}
