import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/*
 *  Klasa ZmienFilmy
 *
 *  Klasa pozwala na stworzenie, zmiane oraz usuniecie filmow, oraz na
 *  przegladanie listy filmow.
 *
 *  Autor: Adam Filipowicz
 *  Data: 2 sierpnia 2017 r.
 */
public class ZmienFilmy extends javax.swing.JFrame {
    private String nazwaKonta;
    protected static OpcjeS opcje;
    private int numerStrony;
    private int iloscFilmu;
    protected Wypozyczalnia wypozyczalnia;
    protected static JOptionUserDialog UI = new JOptionUserDialog();
    
    private ZmienFilmy() {}
    
    public ZmienFilmy(String nazwaKonta, Wypozyczalnia wypozyczalnia) throws SQLException{
        initComponents();
        this.nazwaKonta = nazwaKonta;
        this.wypozyczalnia = wypozyczalnia;
        numerStrony=1;
        aktualizujFilmyIDostepnosc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        iloscText = new javax.swing.JTextField();
        opisText = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        stworzButton = new javax.swing.JButton();
        nazwaText = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        film1Button = new javax.swing.JButton();
        film2Button = new javax.swing.JButton();
        film3Button = new javax.swing.JButton();
        film4Button = new javax.swing.JButton();
        film5Button = new javax.swing.JButton();
        poprzedniaStronaButton = new javax.swing.JButton();
        nastepnaStronaButton = new javax.swing.JButton();
        numerStronyText = new javax.swing.JTextField();
        niedostepny1Text = new javax.swing.JTextField();
        niedostepny2Text = new javax.swing.JTextField();
        niedostepny3Text = new javax.swing.JTextField();
        niedostepny4Text = new javax.swing.JTextField();
        niedostepny5Text = new javax.swing.JTextField();
        cenaText = new javax.swing.JTextField();
        wrocSButton = new javax.swing.JButton();
        zmienButton = new javax.swing.JButton();
        usunButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Edytuj filmy");

        jTextField5.setEditable(false);
        jTextField5.setText("Nazwa filmu");

        jTextField6.setEditable(false);
        jTextField6.setText("Ilosc");

        jTextField7.setEditable(false);
        jTextField7.setText("Cena");

        jTextField8.setEditable(false);
        jTextField8.setText("Opis");

        stworzButton.setText("Stworz");
        stworzButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stworzButtonActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setText("Lista filmow:");

        film1Button.setEnabled(false);

        film2Button.setEnabled(false);

        film3Button.setEnabled(false);

        film4Button.setEnabled(false);

        film5Button.setEnabled(false);

        poprzedniaStronaButton.setText("Poprzednia strona");
        poprzedniaStronaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poprzedniaStronaButtonActionPerformed(evt);
            }
        });

        nastepnaStronaButton.setText("Nastepna strona");
        nastepnaStronaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nastepnaStronaButtonActionPerformed(evt);
            }
        });

        numerStronyText.setEditable(false);
        numerStronyText.setText("Strona: ");

        niedostepny1Text.setEditable(false);

        niedostepny2Text.setEditable(false);

        niedostepny3Text.setEditable(false);

        niedostepny4Text.setEditable(false);

        niedostepny5Text.setEditable(false);

        wrocSButton.setText("Wroc do konta sprzedawcy");
        wrocSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrocSButtonActionPerformed(evt);
            }
        });

        zmienButton.setText("Zmien");
        zmienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmienButtonActionPerformed(evt);
            }
        });

        usunButton.setText("Usun");
        usunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nazwaText)
                                    .addComponent(iloscText)
                                    .addComponent(opisText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cenaText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stworzButton)
                                .addGap(18, 18, 18)
                                .addComponent(zmienButton)
                                .addGap(27, 27, 27)
                                .addComponent(usunButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(niedostepny1Text)
                                    .addComponent(niedostepny5Text)
                                    .addComponent(niedostepny4Text)
                                    .addComponent(niedostepny3Text)
                                    .addComponent(niedostepny2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(film3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(film2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(film1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(film4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(film5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(numerStronyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(114, 114, 114))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(poprzedniaStronaButton)
                                    .addGap(151, 151, 151))
                                .addComponent(nastepnaStronaButton, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(wrocSButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(niedostepny1Text)
                    .addComponent(film1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(film2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(niedostepny2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(film3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(niedostepny3Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(niedostepny4Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(film4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(film5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(niedostepny5Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(numerStronyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nazwaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cenaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iloscText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opisText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stworzButton)
                            .addComponent(zmienButton)
                            .addComponent(usunButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(poprzedniaStronaButton)
                    .addComponent(nastepnaStronaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(wrocSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stworzButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stworzButtonActionPerformed
        try {
            wypozyczalnia.dodajFilm(nazwaText.getText(), Double.parseDouble(cenaText.getText()), Integer.parseInt(iloscText.getText()), opisText.getText());
        } catch (Exception e) {
            UI.printErrorMessage(e.getMessage());
            return;
        }
        try {
            aktualizujFilmyIDostepnosc();
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
        UI.printInfoMessage("Film zostal dodany");
    }//GEN-LAST:event_stworzButtonActionPerformed

    private void poprzedniaStronaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poprzedniaStronaButtonActionPerformed
        if(numerStrony>1){
            numerStrony--;
            try {
                aktualizujFilmyIDostepnosc();
            } catch (Exception ex) {
                UI.printErrorMessage(ex.getMessage());
                return;
            }
        }
    }//GEN-LAST:event_poprzedniaStronaButtonActionPerformed

    private void nastepnaStronaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nastepnaStronaButtonActionPerformed
        numerStrony++;
        try {
            aktualizujFilmyIDostepnosc();
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
    }//GEN-LAST:event_nastepnaStronaButtonActionPerformed

    private void wrocSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrocSButtonActionPerformed
        try {
            opcje = new OpcjeS(nazwaKonta, wypozyczalnia);
        } catch (Exception e) {
            UI.printErrorMessage(e.getMessage());
            return;
        }
        opcje.setResizable(false);
        opcje.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        opcje.setSize(800,500);
        opcje.setLocation(500,250);
        opcje.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_wrocSButtonActionPerformed

    private void zmienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmienButtonActionPerformed
        try {
            wypozyczalnia.zmienFilm(nazwaText.getText(), Double.parseDouble(cenaText.getText()), Integer.parseInt(iloscText.getText()), opisText.getText());
        } catch (Exception e) {
            UI.printErrorMessage(e.getMessage());
            return;
        }
        try {
            aktualizujFilmyIDostepnosc();
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
        UI.printInfoMessage("Film zostal zmieniony");
    }//GEN-LAST:event_zmienButtonActionPerformed

    private void usunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunButtonActionPerformed
        try {
            wypozyczalnia.wycofajFilm(nazwaText.getText());
        } catch (Exception e) {
            UI.printErrorMessage(e.getMessage());
            return;
        }
        try {
            aktualizujFilmyIDostepnosc();
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
        UI.printInfoMessage("Film zostal usuniety");
    }//GEN-LAST:event_usunButtonActionPerformed

    public void aktualizujFilmyIDostepnosc() throws SQLException{
        numerStronyText.setText("Strona: "+numerStrony);
        film1Button.setText(wypozyczalnia.znajdzNazweFilmu((numerStrony-1)*5));
        film2Button.setText(wypozyczalnia.znajdzNazweFilmu((numerStrony-1)*5+1));
        film3Button.setText(wypozyczalnia.znajdzNazweFilmu((numerStrony-1)*5+2));
        film4Button.setText(wypozyczalnia.znajdzNazweFilmu((numerStrony-1)*5+3));
        film5Button.setText(wypozyczalnia.znajdzNazweFilmu((numerStrony-1)*5+4));
        if(film1Button.getText()==null){
            niedostepny1Text.setText("");
        }
        else{
            iloscFilmu=wypozyczalnia.znajdzIloscFilmu(film1Button.getText());
            if(iloscFilmu==0){
                niedostepny1Text.setText("NIEDOSTEPNY");
            }
            else{
                niedostepny1Text.setText("Liczba sztuk: "+iloscFilmu);
            }
        }
        if(film2Button.getText()==null){
            niedostepny2Text.setText("");
        }
        else{
            iloscFilmu=wypozyczalnia.znajdzIloscFilmu(film2Button.getText());
            if(iloscFilmu==0){
                niedostepny2Text.setText("NIEDOSTEPNY");
            }
            else{
                niedostepny2Text.setText("Liczba sztuk: "+iloscFilmu);
            }
        }
        if(film3Button.getText()==null){
            niedostepny3Text.setText("");
        }
        else{
            iloscFilmu=wypozyczalnia.znajdzIloscFilmu(film3Button.getText());
            if(iloscFilmu==0){
                niedostepny3Text.setText("NIEDOSTEPNY");
            }
            else{
                niedostepny3Text.setText("Liczba sztuk: "+iloscFilmu);
            }
        }
        if(film4Button.getText()==null){
            niedostepny4Text.setText("");
        }
        else{
            iloscFilmu=wypozyczalnia.znajdzIloscFilmu(film4Button.getText());
            if(iloscFilmu==0){
                niedostepny4Text.setText("NIEDOSTEPNY");
            }
            else{
                niedostepny4Text.setText("Liczba sztuk: "+iloscFilmu);
            }
        }
        if(film5Button.getText()==null){
            niedostepny5Text.setText("");
        }
        else{
            iloscFilmu=wypozyczalnia.znajdzIloscFilmu(film5Button.getText());
            if(iloscFilmu==0){
                niedostepny5Text.setText("NIEDOSTEPNY");
            }
            else{
                niedostepny5Text.setText("Liczba sztuk: "+iloscFilmu);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZmienFilmy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZmienFilmy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZmienFilmy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZmienFilmy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZmienFilmy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cenaText;
    private javax.swing.JButton film1Button;
    private javax.swing.JButton film2Button;
    private javax.swing.JButton film3Button;
    private javax.swing.JButton film4Button;
    private javax.swing.JButton film5Button;
    private javax.swing.JTextField iloscText;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton nastepnaStronaButton;
    private javax.swing.JTextField nazwaText;
    private javax.swing.JTextField niedostepny1Text;
    private javax.swing.JTextField niedostepny2Text;
    private javax.swing.JTextField niedostepny3Text;
    private javax.swing.JTextField niedostepny4Text;
    private javax.swing.JTextField niedostepny5Text;
    private javax.swing.JTextField numerStronyText;
    private javax.swing.JTextField opisText;
    private javax.swing.JButton poprzedniaStronaButton;
    private javax.swing.JButton stworzButton;
    private javax.swing.JButton usunButton;
    private javax.swing.JButton wrocSButton;
    private javax.swing.JButton zmienButton;
    // End of variables declaration//GEN-END:variables
}
